import type { Config } from 'tailwindcss';
import { theme as designTokens } from './lib/theme';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: { DEFAULT: '1rem', md: '1.5rem', lg: '2rem' },
      screens: { '2xl': '1320px' },
    },
    screens: designTokens.breakpoints,
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        surface: {
          DEFAULT: 'hsl(var(--surface))',
          alt: 'hsl(var(--surface-alt))',
          muted: 'hsl(var(--surface-muted))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          50:  designTokens.colors.primary[50],
          100: designTokens.colors.primary[100],
          200: designTokens.colors.primary[200],
          300: designTokens.colors.primary[300],
          400: designTokens.colors.primary[400],
          500: designTokens.colors.primary[500],
          600: designTokens.colors.primary[600],
          700: designTokens.colors.primary[700],
          800: designTokens.colors.primary[800],
          900: designTokens.colors.primary[900],
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
          50:  designTokens.colors.accent[50],
          100: designTokens.colors.accent[100],
          200: designTokens.colors.accent[200],
          300: designTokens.colors.accent[300],
          400: designTokens.colors.accent[400],
          500: designTokens.colors.accent[500],
          600: designTokens.colors.accent[600],
          700: designTokens.colors.accent[700],
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        warning: {
          DEFAULT: designTokens.colors.warning[400],
          foreground: designTokens.colors.neutral[900],
          50:  designTokens.colors.warning[50],
          100: designTokens.colors.warning[100],
          400: designTokens.colors.warning[400],
          500: designTokens.colors.warning[500],
        },
        success: {
          DEFAULT: designTokens.colors.success[500],
          foreground: designTokens.colors.neutral[0],
          50:  designTokens.colors.success[50],
          100: designTokens.colors.success[100],
          500: designTokens.colors.success[500],
          600: designTokens.colors.success[600],
          700: designTokens.colors.success[700],
        },
      },
      fontFamily: designTokens.typography.fontFamily,
      fontWeight: designTokens.typography.fontWeight,
      borderRadius: {
        none: designTokens.radius.none,
        xs:   designTokens.radius.xs,
        sm:   'calc(var(--radius) - 4px)',
        md:   'calc(var(--radius) - 2px)',
        lg:   'var(--radius)',
        xl:   designTokens.radius.xl,
        '2xl':designTokens.radius['2xl'],
        '3xl':designTokens.radius['3xl'],
        pill: designTokens.radius.pill,
      },
      boxShadow: {
        xs:    designTokens.shadows.xs,
        sm:    designTokens.shadows.sm,
        card:  designTokens.shadows.card,
        DEFAULT: designTokens.shadows.sm,
        md:    designTokens.shadows.md,
        lg:    designTokens.shadows.lg,
        xl:    designTokens.shadows.xl,
        inner: designTokens.shadows.inner,
        focus: designTokens.shadows.focus,
      },
      transitionTimingFunction: designTokens.animation.easing,
      transitionDuration: designTokens.animation.duration,
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'pulse-soft': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 200ms ease-out',
        'slide-up': 'slide-up 240ms cubic-bezier(0.4, 0, 0.2, 1)',
        'pulse-soft': 'pulse-soft 2.4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, hsl(var(--primary)) 0%, hsl(var(--accent)) 100%)',
        'gradient-hero':    'linear-gradient(135deg, #0B1E3D 0%, #1F4A8D 60%, #2A5FA8 100%)',
        'gradient-soft':    'linear-gradient(180deg, hsl(var(--surface-alt)) 0%, hsl(var(--background)) 100%)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
